fflch/orcamento

.gitignore, app/Http/Controllers/IndexController.php, app/Providers/AppServiceProvider.php, composer.json, composer.lock, resources/views/index.blade.php, resources/views/master.blade.php, resources/views/messages/errors.blade.php, resources/views/messages/flash.blade.php, routes/web.php
Fix #1 
Refiz tudo num novo projeto. Essa primeira solicitação de revisão é só pra reforçar o processo dos pull requests. Os próximos, eu mesmo aprovo.
=> Implementado IndexController

app/Http/Controllers/TipoContaController.php, app/TipoConta.php, database/migrations/2020_04_06_190850_create_tipo_contas_table.php, resources/views/movimentos/show.blade.php, resources/views/tipocontas/create.blade.php, resources/views/tipocontas/edit.blade.php, resources/views/tipocontas/form.blade.php, resources/views/tipocontas/index.blade.php, resources/views/tipocontas/show.blade.php, routes/web.php
Fix #7 
Foram feitas pequenas correções em dois arquivos referentes ao CRUD Movimento
=> Implementado CRUD Tipos de Contas

app/Area.php, app/Http/Controllers/AreaController.php, database/migrations/2020_04_08_121347_create_areas_table.php, resources/views/areas/create.blade.php, resources/views/areas/edit.blade.php, resources/views/areas/form.blade.php, resources/views/areas/index.blade.php, resources/views/areas/show.blade.php, routes/web.php
=> Implementando CRUD Áreas

app/DotOrcamentaria.php, app/Http/Controllers/DotOrcamentariaController.php, database/migrations/2020_04_08_174932_create_dot_orcamentarias_table.php, resources/views/dotorcamentarias/create.blade.php, resources/views/dotorcamentarias/edit.blade.php, resources/views/dotorcamentarias/form.blade.php, resources/views/dotorcamentarias/index.blade.php, resources/views/dotorcamentarias/show.blade.php, routes/web.php
=> Implementando CRUD Dotação Orçamentária

database/factories/MovimentoFactory.php, database/seeds/DatabaseSeeder.php, database/seeds/MovimentoSeeder.php
=> Implementado Seed e Factory - Movimentos

database/factories/AreaFactory.php, database/seeds/AreaSeeder.php, database/seeds/DatabaseSeeder.php
=> Implementado Seed e Factory - Áreas

database/factories/TipoContaFactory.php, database/seeds/DatabaseSeeder.php, database/seeds/TipoContaSeeder.php
=> Implementado Seed e Factory - Tipos de Contas

database/factories/DotOrcamentariaFactory.php, database/seeds/DatabaseSeeder.php, database/seeds/DotOrcamentariaSeeder.php
=> Implementado Seed e Factory - Dotações Orçamentárias

app/Http/Controllers/AreaController.php, app/Http/Controllers/DotOrcamentariaController.php, app/Http/Controllers/MovimentoController.php, app/Http/Controllers/TipoContaController.php, resources/views/areas/index.blade.php, resources/views/dotorcamentarias/index.blade.php, resources/views/movimentos/index.blade.php, resources/views/tipocontas/index.blade.php
Movimentos, Áreas, Tipos de Contas e Dotações Orçamentárias
Fix #22
=> Implementada Paginação

app/Http/Controllers/AreaController.php, app/Http/Controllers/DotOrcamentariaController.php, app/Http/Controllers/MovimentoController.php, app/Http/Controllers/TipoContaController.php, resources/views/areas/index.blade.php, resources/views/dotorcamentarias/index.blade.php, resources/views/movimentos/index.blade.php, resources/views/tipocontas/index.blade.php
Movimentos, Áreas Tipos de Contas e Dotações Orçamentárias
Fix #24
=> Implementada Busca

app/Http/Controllers/AreaController.php, app/Http/Controllers/DotOrcamentariaController.php, app/Http/Controllers/MovimentoController.php, app/Http/Controllers/TipoContaController.php, app/Http/Requests/AreaRequest.php, app/Http/Requests/DotOrcamentariaRequest.php, app/Http/Requests/MovimentoRequest.php, app/Http/Requests/TipoContaRequest.php
Movimentos, Áreas, Tipos de Contas e Dotações Orçamentárias
Fix #26
=> Implementada Validação

app/Http/Controllers/AreaController.php, app/Http/Controllers/DotOrcamentariaController.php, app/Http/Controllers/MovimentoController.php, app/Http/Controllers/TipoContaController.php, app/Http/Requests/AreaRequest.php, app/Http/Requests/DotOrcamentariaRequest.php, app/Http/Requests/MovimentoRequest.php, app/Http/Requests/TipoContaRequest.php, app/Models/Area.php, app/Models/DotOrcamentaria.php, app/Models/Movimento.php, app/Models/TipoConta.php, database/migrations/2020_04_02_132746_create_movimentos_table.php, resources/views/areas/show.blade.php, resources/views/dotorcamentarias/show.blade.php, resources/views/movimentos/form.blade.php, resources/views/movimentos/index.blade.php, resources/views/movimentos/show.blade.php, resources/views/tipocontas/show.blade.php
=> Bootstrap e validação

app/Http/Controllers/ContaController.php, app/Http/Controllers/selTipoContaController.php, app/Http/Requests/ContaRequest.php, app/Http/Requests/TipoContaRequest.php, app/Models/Area.php, app/Models/Conta.php, app/Models/Movimento.php, app/Models/TipoConta.php, config/laravel-usp-theme.php, database/factories/ContaFactory.php, database/factories/UserFactory.php, database/migrations/2014_10_12_000000_create_users_table.php, database/migrations/2020_04_02_132746_create_movimentos_table.php, database/migrations/2020_04_06_190850_create_tipo_contas_table.php, database/migrations/2020_04_08_121347_create_areas_table.php, database/migrations/2020_10_23_210510_create_contas_table.php, database/seeders/ContaSeeder.php, database/seeders/DatabaseSeeder.php, resources/views/contas/create.blade.php, resources/views/contas/edit.blade.php, resources/views/contas/form.blade.php, resources/views/contas/index.blade.php, resources/views/contas/show.blade.php, resources/views/selTipoConta.blade.php, routes/web.php
=> Implementado CRUD, Seeder e Faker para Contas

app/Http/Controllers/NotaController.php, app/Http/Requests/NotaRequest.php, app/Models/Nota.php, config/laravel-usp-theme.php, database/factories/DotOrcamentariaFactory.php, database/factories/NotaFactory.php, database/migrations/2014_10_12_000000_create_users_table.php, database/migrations/2020_04_02_132746_create_movimentos_table.php, database/migrations/2020_04_06_190850_create_tipo_contas_table.php, database/migrations/2020_04_08_121347_create_areas_table.php, database/migrations/2020_10_29_122531_create_notas_table.php, database/seeders/ContaSeeder.php, database/seeders/DatabaseSeeder.php, database/seeders/NotaSeeder.php, database/seeders/UserSeeder.php, resources/views/notas/create.blade.php, resources/views/notas/edit.blade.php, resources/views/notas/form.blade.php, resources/views/notas/index.blade.php, resources/views/notas/show.blade.php, routes/web.php
=> CRUD, Seeder, Faker Descrições e Observações-Notas

app/Http/Controllers/ContaController.php, app/Http/Controllers/LancamentoController.php, app/Http/Requests/ContaRequest.php, app/Http/Requests/LancamentoRequest.php, app/Http/Requests/NotaRequest.php, app/Models/Conta.php, app/Models/Lancamento.php, app/Models/Nota.php, config/laravel-usp-theme.php, database/factories/LancamentoFactory.php, database/migrations/2020_10_29_122531_create_notas_table.php, database/migrations/2020_11_03_175520_create_lancamentos_table.php, database/seeders/ContaSeeder.php, database/seeders/DatabaseSeeder.php, database/seeders/LancamentoSeeder.php, database/seeders/NotaSeeder.php, resources/views/lancamentos/create.blade.php, resources/views/lancamentos/edit.blade.php, resources/views/lancamentos/form.blade.php, resources/views/lancamentos/index.blade.php, resources/views/lancamentos/show.blade.php, routes/web.php
=> CRUD, Seeder, Faker para Lançamentos

app/Http/Controllers/FicOrcamentariaController.php, app/Http/Requests/FicOrcamentariaRequest.php, app/Models/DotOrcamentaria.php, app/Models/FicOrcamentaria.php, config/laravel-usp-theme.php, database/factories/DotOrcamentariaFactory.php, database/factories/FicOrcamentariaFactory.php, database/migrations/2020_04_08_174932_create_dot_orcamentarias_table.php, database/migrations/2020_11_05_132405_create_fic_orcamentarias_table.php, database/seeders/DatabaseSeeder.php, database/seeders/DotOrcamentariaSeeder.php, database/seeders/FicOrcamentariaSeeder.php, resources/views/ficorcamentarias/create.blade.php, resources/views/ficorcamentarias/edit.blade.php, resources/views/ficorcamentarias/form.blade.php, resources/views/ficorcamentarias/index.blade.php, resources/views/ficorcamentarias/show.blade.php, routes/web.php
=> CRUD, Seeder e Faker - Ficha Orçamentária

app/Http/Controllers/ContaUsuarioController.php, app/Http/Requests/ContaUsuarioRequest.php, app/Models/ContaUsuario.php, app/Models/User.php, config/laravel-usp-theme.php, database/factories/ContaUsuarioFactory.php, database/migrations/2020_11_06_132439_create_conta_usuarios_table.php, database/seeders/ContaUsuarioSeeder.php, database/seeders/DatabaseSeeder.php, resources/views/contausuarios/create.blade.php, resources/views/contausuarios/edit.blade.php, resources/views/contausuarios/form.blade.php, resources/views/contausuarios/index.blade.php, resources/views/contausuarios/show.blade.php, routes/web.php
=> CRUD, Seeder e Faker - Contas x Usuários

app/Http/Controllers/NotaController.php, app/Http/Requests/NotaRequest.php, app/Models/FicOrcamentaria.php, app/Models/Lancamento.php, app/Models/Nota.php, database/factories/NotaFactory.php, database/migrations/2020_10_29_122531_create_notas_table.php, database/migrations/2020_11_02_132405_create_fic_orcamentarias_table.php, database/migrations/2020_11_03_175520_create_lancamentos_table.php, database/seeders/NotaSeeder.php, resources/views/notas/form.blade.php
=> Campo Select e Mutators

app/Http/Controllers/ContaUsuarioController.php, app/Http/Controllers/LoginController.php, app/Models/ContaUsuario.php, composer.lock, config/laravel-usp-theme.php, routes/web.php
=> Resolvido problema com logout e outros problemas.

app/Http/Controllers/UnidadeController.php, app/Http/Requests/ContaRequest.php, app/Http/Requests/UnidadeRequest.php, app/Models/Unidade.php, config/laravel-usp-theme.php, database/migrations/2020_12_14_141110_create_unidades_table.php, database/seeders/DatabaseSeeder.php, database/seeders/UnidadeSeeder.php, resources/views/index.blade.php, resources/views/master.blade.php, resources/views/unidades/edit.blade.php, resources/views/unidades/form.blade.php, resources/views/unidades/index.blade.php, resources/views/unidades/show.blade.php, routes/web.php
=> Implementado Model para Unidade

app/Http/Controllers/FicOrcamentariaController.php, app/Http/Controllers/LancamentoController.php, app/Http/Requests/LancamentoRequest.php, app/Models/FicOrcamentaria.php, app/Models/Lancamento.php, resources/views/ficorcamentarias/formcp.blade.php, resources/views/ficorcamentarias/show.blade.php, resources/views/lancamentos/form.blade.php, resources/views/lancamentos/partials/percentual.blade.php, resources/views/lancamentos/show.blade.php
Foi alterada a maneira de definir os "percentuais" dentro do lançamento. Foi corrigida a função "calculaSaldo()" no model do lançamento. Por fim, há coisas inacabadas na parte referente as Fichas Orçamentárias.
fix #92
=> Refatorar lançamento

app/Http/Controllers/FicOrcamentariaController.php, app/Http/Controllers/LancamentoController.php, app/Http/Requests/FicOrcamentariaCPRequest.php, app/Http/Requests/LancamentoRequest.php, app/Rules/PercentualRule.php, app/Rules/ValorRule.php, resources/views/ficorcamentarias/form.blade.php, resources/views/ficorcamentarias/formcp.blade.php, resources/views/ficorcamentarias/show.blade.php, resources/views/lancamentos/edit.blade.php, resources/views/lancamentos/formedit.blade.php, resources/views/lancamentos/partials/percentualedit.blade.php
Foi colocado um foreach na view de editar os lançamentos, para que sejam puxados todos os percentuais vinculados a um lançamento. 
P.S: Essa view foi replicada, para que não houvesse necessidade de considerar a situação onde não é tela de editar mas sim de cadastrar.
Foram colocadas duas rules: uma para validação de percentuais(lançamentos) e outra para de contra-partidas(fichas orçamentárias).
Por fim, foram consertados alguns erros e/ou linhas desnecessárias notados em momentos diversos.
=> Consertando erros e fazendo validações

app/Http/Controllers/LancamentoController.php, resources/views/contas/form.blade.php, resources/views/lancamentos/form.blade.php, resources/views/lancamentos/index.blade.php
Foram feitos pequenos reparos de alguns erros encontrados na revisão do homolog do sistema de orçamentos.
=> Pequenos reparos

app/Http/Requests/FicOrcamentariaRequest.php, database/migrations/2020_11_02_132405_create_fic_orcamentarias_table.php, database/migrations/2020_11_03_175520_create_lancamentos_table.php
Coloquei a validação do campo "empenho" da Ficha Orçamentária como nullable, igual é feito no Lançamento.
=> arrumando validação do campo empenho

app/Http/Controllers/LoginController.php, app/Http/Controllers/MovimentoController.php, app/Http/Requests/MovimentoRequest.php, app/Models/Movimento.php, app/Services/MovimentoService.php, database/factories/MovimentoFactory.php, database/migrations/2020_04_02_132746_create_movimentos_table.php, database/seeders/MovimentoSeeder.php, resources/views/alternateindex.blade.php, resources/views/index.blade.php, resources/views/movimentos/form.blade.php, resources/views/movimentos/index.blade.php, resources/views/movimentos/show.blade.php
-> Foi retirada a opção de marcar um ano/movimento como concluído, por pedido do pessoal da Contabilidade;
-> Foi feito um Service onde o ano atual é automaticamente criado e/ou colocado como ativo, caso, respectivamente, não exista ou exista e não esteja ativado;
-> Foi colocada uma view que retorna uma mensagem para que se contate o pessoal da Contabilidade, pois o Service só cria o ano caso o usuário que logue seja Administrador. Ou seja, em caso contrário, o usuário é deslogado e tem como retorno essa view.
=> Retirando campo  "concluído" e adicionando MovimentoService

app/Http/Controllers/UserController.php, resources/views/usuarios/edit.blade.php
Algumas alterações solicitadas na reunião Laravel de 09/11/2023
-> Mostrar id da conta e não da conta x usuário;
-> Retirar paginate.
=> Alterações solicitadas em reunião

app/Console/Commands/ImportData.php
-> Foi adicionada a função que importa o banco de dados do sistema que está atualmente no ar;
-> Uma parte do código faz o insert para a tabela pivot que não existia anteriormente.
=> Importação de dados

app/Http/Controllers/ContaController.php, app/Http/Controllers/DotOrcamentariaController.php, app/Http/Controllers/LancamentoController.php, app/Http/Controllers/RelatorioController.php, database/migrations/2022_11_18_143047_create_conta_lancamento_table.php, resources/views/dotorcamentarias/index.blade.php, resources/views/ficorcamentarias/index_por_dotacao.blade.php, resources/views/lancamentos/index_por_conta.blade.php, resources/views/lancamentos/show.blade.php, resources/views/relatorios/index.blade.php, routes/web.php
Foram alterados os seguintes tópicos, solicitados na última reunião com o setor da contabilidade:
-> Inserção de um filtro por ano escolhido na sessão na view de lançamentos por conta;
-> Inserção de uma view com fichas orçamentárias filtradas por dotação;
-> Consertado o método de deletar um percentual - colocadas as chaves estrangeiras da tabela pivot como primary keys;
-> Inserção de filtro por ano escolhido na sessão na aba de emissão de relatórios.
=> Alterações/Reparos da última reunião reunião

app/Http/Controllers/FicOrcamentariaController.php, app/Http/Controllers/RelatorioController.php, app/Http/Requests/FicOrcamentariaCPRequest.php, app/Http/Requests/PercentualRequest.php, resources/views/ficorcamentarias/formcp.blade.php, resources/views/lancamentos/partials/percentual.blade.php, resources/views/pdfs/acompanhamento.blade.php, resources/views/pdfs/despesas_miudas.blade.php, resources/views/relatorios/indexacompanhamento.blade.php, resources/views/relatorios/indexlancamentos.blade.php
Foi feito:
-> Conserto dos pdfs de alguns dos relatórios;
-> Aplicação de um filtro por período de tempo na emissão dos pdfs referentes a Acompanhamento e Lançamentos, por conta da quantidade de registros - o cálculo desse ainda falta passar para uma Rule;
-> Acrescentada a função old e suas exigências nos arquivos blade "percentual" (Lançamentos) e "formcp" (Fichas Orçamentárias).
=> Consertando relatorios

app/Http/Controllers/FicOrcamentariaController.php, app/Http/Requests/FicOrcamentariaCPRequest.php, resources/views/ficorcamentarias/index.blade.php, resources/views/ficorcamentarias/index_por_dotacao.blade.php, resources/views/ficorcamentarias/show.blade.php, resources/views/lancamentos/index.blade.php, resources/views/lancamentos/index_por_conta.blade.php
Foi feito, a pedido do pessoal da Contabilidade:
-> Inserção do campo "Observação" no index de Fichas Orçamentárias e Lançamentos;
-> Inserção do nome da conta a qual uma Contra-partida de Ficha Orçamentária está vinculada;
-> Remoção da parte do código que chama a rule de verificação de valor cadastrado em uma Contra-partida, na Ficha Orçamentária.
=> Inserindo campo "observação", desativando rule e acrescentando nome da conta da contra-partida

app/Http/Controllers/LancamentoUserController.php, app/Http/Controllers/RelatorioController.php, resources/views/lancamentosuser/index.blade.php, resources/views/pdfs/balancete.blade.php, resources/views/pdfs/lancamentos.blade.php
Foi consertado o pdf que apresenta o balancete até determinada data, assim como o index/pdf dos Lançamentos, para que multiplique o valor lançado pelo percentual referente ao mesmo.
=> Arrumando balancete e index de lançamentos

app/Http/Controllers/DotOrcamentariaController.php, app/Http/Controllers/LancamentoController.php, app/Http/Controllers/RelatorioController.php, resources/views/contas/index.blade.php, resources/views/dotorcamentarias/index.blade.php, resources/views/lancamentos/index.blade.php, resources/views/lancamentos/show.blade.php, resources/views/pdfs/acompanhamento.blade.php, resources/views/relatorios/indexacompanhamento.blade.php
Foi feito:
-> Inserção de busca por Grupo no index de Lançamentos e Dotações Orçamentárias; 
-> Redefinida a data filtro do PDF Acompanhamento para apenas uma, ao invés de duas;
-> Verificação da data escolhida no Acompanhamento com o ano escolhido na sessão; 
-> Verificação provisória: if que certifica se a data foi inserida ao emitir PDF de Lançamentos ou Ficha Orçamentária - será passado para formRequest; 
-> Reformulação do código que gera o PDF de Fichas Orçamentárias; 
-> O campo Saldo, dos Lançamentos, foi configurado para aparecer somente caso submeta-se uma busca, pois caso contrário não é para ser calculado.
=> Acrescentando campo em buscas; modificando index; reformulação de código; verificações

resources/views/pdfs/balancete.blade.php, resources/views/pdfs/ficha_orcamentaria.blade.php, resources/views/pdfs/lancamentos.blade.php
-> Colocando tabela de Totais Gerais no relatório de Lançamentos e Fichas Orçamentárias; 
-> Consertando tabela no PDF Balancete - não precisava fazer uma tabela nova, apenas acrescentar <tr>.
=> Acrescentando "Totais Gerais" no PDF de Lançamento/Ficha; melhorando o PDF do Balancete

app/Http/Controllers/ContaController.php, app/Http/Controllers/LancamentoController.php, app/Http/Controllers/RelatorioController.php, app/Services/Query.php, resources/views/lancamentos/index.blade.php, resources/views/lancamentos/index_por_conta.blade.php, resources/views/lancamentos/show.blade.php, resources/views/lancamentosuser/index.blade.php, resources/views/pdfs/acompanhamento.blade.php
-> Foi inserida a segunda parte do PDF de Acompanhamentos; 
-> Foi reparada a parte do código que calcula o saldo dos lançamentos, no index dos mesmos; 
-> Foram reparadas algumas coisas no index do usuário comum, como a fixação da data em caso de erro ou pesquisa;
-> Tirado o campo de saldo do index de lançamentos até que o mesmo esteja sendo exibido corretamente.
=> PDF Acompanhamento; arrumando saldo dos lançamentos e index lançamentos/usuarios

app/Http/Controllers/ContaController.php, app/Http/Controllers/DotOrcamentariaController.php, app/Http/Controllers/FicOrcamentariaController.php, app/Http/Controllers/LancamentoController.php, app/Http/Controllers/LancamentoUserController.php, app/Http/Controllers/RelatorioController.php, app/Services/FicOrcamentariaService.php, app/Services/LancamentoService.php, resources/views/ficorcamentarias/index.blade.php, resources/views/ficorcamentarias/index_por_dotacao.blade.php, resources/views/lancamentos/index.blade.php, resources/views/lancamentos/index_por_conta.blade.php, resources/views/lancamentosuser/index.blade.php, resources/views/pdfs/ficha_orcamentaria.blade.php, resources/views/pdfs/lancamentos.blade.php
-> Lançamentos;
-> Ficha Orçamentária;
-> PDFs dos dois acima mencionados
=> Implementando campo Saldo nos seus respectivos index

app/Http/Controllers/FicOrcamentariaController.php, app/Http/Controllers/LancamentoController.php, app/Models/FicOrcamentaria.php, app/Models/Lancamento.php, composer.json, composer.lock, database/migrations/2024_04_30_145647_drop_saldo_column_in_lancamentos.php, database/migrations/2024_04_30_150009_drop_saldo_column_in_ficorcamentarias.php, resources/views/ficorcamentarias/show.blade.php, resources/views/lancamentos/show.blade.php
A coluna foi retirada, pois não está em uso.
=> Migration de alteração - retirando coluna "saldo" das tabelas "lancamentos" e "fic_orcamentarias"

resources/views/lancamentos/partials/filtro.blade.php, resources/views/pdfs/acompanhamento.blade.php, resources/views/pdfs/balancete.blade.php, resources/views/pdfs/ficha_orcamentaria.blade.php, resources/views/pdfs/lancamentos.blade.php, resources/views/pdfs/saldo_contas.blade.php, resources/views/pdfs/saldo_dotacoes.blade.php, resources/views/relatorios/indexlancamentos.blade.php
Foi feito:
-> Agora é possível digitar nos campos selects responsáveis pelo filtro ao emitir um relatório (PDF); 
-> Diminuição do título dos PDFs.
=> Possibilitando digitação nos selects e diminuindo título do PDF 

README.md
=> atualização do README.md do orçamento com a descrição das funções do sistema e de seus Models

app/Http/Controllers/RelatorioController.php
=> Aplicando filtro por ano na função que gera o PDF dos lançamentos

app/Http/Controllers/RelatorioController.php, app/Services/MovimentoService.php
foi criada uma nova função na classe MovimentoService para retornar o ano ativo da sessão. Isso foi necessário para corrigir o relatório da ficha orçamentária.
=> corrigindo relatório da ficha orçamentária
